### ISSUE TITLE
Bug fix in `infer_mixture` lines 288-291, setting lambda from pi_prior

### ISSUE THREAD

**Issue by krshedd** [eriqande/rubias#21]
It looks like there is a small error in specifying `lambda` from `pi_prior` in lines 288-291 of `infer_mixture` due to some missing {}. Below is how I think it should read with the extra {}. Feel free to close if I am off base.
```
if (identical(pi_prior, NA)) {
      lambda <- rep(pi_prior_sum/params$C, params$C)
    } else {
      if (is.numeric(pi_prior)) {
        lambda <- pi_prior  
      } else {
        lambda <- custom_pi_prior(P = pi_prior, C = data.frame(collection = colnames(ac[[1]])))
      }
    }
```

**Comment by eriqande** [comment]
Hi Kyle,
Thanks for that.  Yes, R as an interpreted language has some funny behavior around else if constructs that can create unexpected results.  This was a section that Ben wrote, and I think it performs as desired, but I do agree that with R it is easier to read the intent with more explicit braces in there for the blocks.  So, I have revised this to:

```r
    if(is.na(pi_prior)) {
      lambda <- rep(pi_prior_sum / params$C, params$C)
    } else {
      if(is.numeric(pi_prior)) {
        lambda <- pi_prior
      } else {
        lambda <- custom_pi_prior(P = pi_prior, C = data.frame(collection = colnames(ac[[1]])))
      }
    }
```

Which gives the same results as before as far as I can tell.

Do you have an example data sets / function call where the old code gives a small error?  Can you let me know if the new version (which I will push up shortly) gives a different result?

The `if(is.numeric(pi_prior))` is in there to be able to use an undocumented way of specifying the prior pseudocounts by just passing a vector in.  That is useful for Ben for development, but not good for users, which is why we don't document it.

**Comment by krshedd** [comment]
Hi Eric,
I hadn't done any explicit testing to see if it produced an error as I have just been using the default pi_prior for now. I was just going through the code in `infer_mixture` to see what objects get passed on to `gsi_mcmc_1` and that section was not clear to me without the extra braces. Sorry if it was a non-issue. Thanks for the heads up regarding the `if(is.numeric(pi_prior))` as that was unclear to me as well.
